### ISSUE TITLE
Defining multiple NodemonPlugin in configuration

### ISSUE THREAD

**Issue by MohammedSiddiqui** [Izhaki/nodemon-webpack-plugin#115]
My webpack configuration has **multiple** entrypoints i.e server.js, sqs_listener.js. If I simply add this kind of configuration, I can see that two processes indeed get initiated.

```
plugins: [
        new NodemonPlugin({
            watch: path.resolve('./build'),
            ignore: ['*.js.map'],
            verbose: false,
            nodeArgs: ['--inspect=0.0.0.0:9229'],
            script: './build/server.js',
            ext: 'js,json,ejs',
        }),
        new NodemonPlugin({
            watch: path.resolve('./build'),
            ignore: ['*.js.map'],
            verbose: false,
            nodeArgs: ['--inspect=0.0.0.0:9228'],
            script: './build/sqs_listener.js',
            ext: 'js,json,ejs',
        })
    ]
```
But it seems that the last one overrules, and one of them crashes.
```
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): build/**/* build/**/*
[nodemon] watching extensions: js,json,ejs
[nodemon] starting `node --inspect=0.0.0.0:9228 ./build/sqs_listener.js`
[nodemon] 2.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): build/**/* build/**/*
[nodemon] watching extensions: js,json,ejs
[nodemon] starting `node --inspect=0.0.0.0:9228 ./build/sqs_listener.js`
Starting inspector on 0.0.0.0:9228 failed: address already in use
[nodemon] app crashed - waiting for file changes before starting...
```
Is there a way we could initiate multiple servers after webpack has done compiling the project ? Perhaps forking it into a child process, as mentioned in nodemon's documentation ?

The most easiest way I could make it run is to create another webpack config and launch it in another terminal in parallel, but webpack redundantly builds the same files, which taxes my CPU quite a bit.

**Comment by Izhaki** [comment]
Wow. That's a first... never thought anyone would use it this way.

My gut feeling is that this has to do with this statement from [Nodemon doc](https://github.com/remy/nodemon/blob/master/doc/requireable.md#nodemon-as-a-required-module):

> At present, you can only require nodemon in to your project once (as there are static config variables), but you can re-run with new settings for a different application to monitor.

But I'm not sure. I guess @remy will be.

**Comment by MohammedSiddiqui** [comment]
Yeah, for now due to Architectural design limitations, we have a single database, but we're trying to slowly split up our monolith Backend API server into smaller chunks, so it's easier to scale them when required. So I added webpack to help with this and create multiple entrypoints, which would help us still reuse our typeorm definitions, repositories and helpers, but give us the capability to have different servers.

Could this help ? 
https://github.com/remy/nodemon/blob/master/doc/events.md#Using_nodemon_as_child_process

**Comment by Izhaki** [comment]
That could work. But child processes come with their own bag of worms...

**Comment by MohammedSiddiqui** [comment]
Agreed ... I'll try it out over the weekend and see if something comes to light. If it works out, would you be willing to make it an official part of this repo ?

**Comment by Izhaki** [comment]
There's a bit of danger in this sort of things:

- First, I need to modify core functionality. While there are tests, there could be platform dependent issues with child process.
- To make this opt-in feature, means a breaking API change.
- I'll need to translate nodemon object to command line...
- Then, there's added code complexity to satisfy some edge case.

I'll be much more inclined to submit a PR to the nodemon repo allowing more than one programmatic lunch than change this plugin.

The real issue is not in the plugin, but rather in nodemon (just think of all other projects using nodemon that may want to run more than one monitor programatically.

**Comment by byzyk** [comment]
@MohammedSiddiqui I'm stuck with the same problem. Were you able to find the solution or maybe have some insights to share? Would really appreciate it thanks :)

**Comment by Izhaki** [comment]
@byzyk 

I'm pretty sure you can write a script that restarts both services? Essentially, a script that spawns two child process, and listens to SIGTERM, which is the signal I believe nodemon sends...

Would be pretty cool if either you or @MohammedSiddiqui attempt this and share here.
