### ISSUE TITLE
Delay for nodemon is not working

### ISSUE THREAD

**Issue by chivong** [Izhaki/nodemon-webpack-plugin#117]
The delay config for nodemon is not working. These are my config
```
new NodemonPlugin({
     delay: 10,
     watch: buildPath,
     script: './dist/server.js',
}),
```
Even with a delay on 10 seconds, I still get a lot of verbose
<img width="560" alt="sc" src="https://user-images.githubusercontent.com/62539847/81280070-45c0b380-9058-11ea-9bf4-16fcaf276aab.png">

**Comment by Izhaki** [comment]
The example given on the [nodemon config page](https://github.com/remy/nodemon#packagejson) is:


```
{
  "name": "nodemon",
  "homepage": "http://nodemon.io",
  "...": "... other standard package.json values",
  "nodemonConfig": {
    "ignore": ["test/*", "docs/*"],
    "delay": "2500"
  }
}
```

The number `2500` suggests these are milliseconds not seconds. So `10` would mean `0.01` seconds, which is not a delay you'll notice. For 10 seconds put `10000`.

Another odd thing about this example is that `2500` it is given as a string, not a number.

So I'd try:

```
new NodemonPlugin({
     delay: 10000,
     watch: buildPath,
     script: './dist/server.js',
}),
```
And if this doesn't work:

```
new NodemonPlugin({
     delay: "10000",
     watch: buildPath,
     script: './dist/server.js',
}),
```

**Comment by chivong** [comment]
Oh, that's confusing since `nodemon --delay 10` is in seconds. Thanks for your answer

**Comment by Izhaki** [comment]
Confusing indeed.

Did it work? Did it need it as string?

Can we close this issue?

**Comment by chivong** [comment]
Yes, it worked well with delay string, not as number. This issue can be closed.

**Comment by Izhaki** [comment]
I've added a delay example to the README.

Thanks!
