### ISSUE TITLE
Typescript errors with Webpack 5

### ISSUE THREAD

**Issue by Izhaki** [Izhaki/nodemon-webpack-plugin#118]
Webpack 5 (5.0.0-beta.16) does not export `Plugin`, which cause type-checking and builds to fail with:

```
node_modules/nodemon-webpack-plugin/dist/index.d.ts:3:12 - error TS2459: Module '"......./node_modules/webpack/types"' declares 'Plugin' locally, but it is not exported.

3   import { Plugin } from 'webpack';
             ~~~~~~

  node_modules/webpack/types.d.ts:5126:19
    5126 declare interface Plugin {
                           ~~~~~~
    'Plugin' is declared here.

node_modules/schema-utils/declarations/validate.d.ts:2:34 - error TS2307: Cannot find module 'json-schema'.

2 export type JSONSchema4 = import('json-schema').JSONSchema4;
                                   ~~~~~~~~~~~~~

node_modules/webpack/types.d.ts:62:8 - error TS2307: Cannot find module 'estree'.

62 } from "estree";
```

Related:
- https://github.com/webpack/webpack/issues/10757#issuecomment-625542931
- https://github.com/webpack/webpack/issues/9802

**Comment by mlegenhausen** [comment]
Changing the typing to the following should work with both versions?

```
declare module 'nodemon-webpack-plugin' {
  import { Settings } from 'nodemon';
  import { Plugin } from 'webpack';

  /**
   * Uses Nodemon to watch and restart your module's output file (presumably a
   * server), but only when webpack is in watch mode (ie, --watch).
   *
   * Saves the need for installing, configuring and running Nodemon as a
   * separate process.
   */
  interface NodemonPlugin {
    new (opts?: Settings): Plugin
  }

  declare const nodemonPlugin: NodemonPlugin
  export default nodemonPlugin
}
```

**Comment by Izhaki** [comment]
Will try to give this a go this tonight/tomorrow.

**Comment by Izhaki** [comment]
Having upgraded `webpack@^5.13.0` the errors are different now.

With or without the propose solution I get:
```
Module '"../node_modules/webpack/types"' has no exported member 'Plugin'.
```

This [types.d.ts](https://github.com/webpack/webpack/blob/v5.13.0/types.d.ts) has all sorts of [Somthing]Plugin declarations but not a 'Plugin' one.

**Comment by Izhaki** [comment]
More of a note to self: html-webpack-plugin does not import the type from webpack, rather it [declares its own](https://github.com/jantimon/html-webpack-plugin/blob/3768bbabb7bfc19487f94841f0e7d4900bca7110/typings.d.ts).

**Comment by Izhaki** [comment]
OK. So the response on Webpack is that in 5 we have [WebpackPluginInstance]()https://github.com/webpack/webpack/blob/v5.13.0/types.d.ts#L10473

**Comment by mlegenhausen** [comment]
Seems they removed the `Plugin` alias in newer versions was a little bit confused cause I didn't get any errors. But it should work with `WebpackPluginInstance` as you mentioned.

**Comment by Izhaki** [comment]
Yeah. The issue is that from 4 to 5 the types has changed and these are breaking changes - so you can't make it work with both 4 & 5...

**Comment by mlegenhausen** [comment]
I think thats why `html-webpack-plugin` defines the `Plugin` by itself?

Or maybe dropping webpack 4 support in the next major version could be reasonable?

**Comment by Izhaki** [comment]
Yeah. I think the only way out of it is not to use WebPack types and define our own.

Dropping 4 - I'm pretty sure many mainstream tools still support it (NextJS for instance).

Found [this approach on NextJS](https://github.com/vercel/next.js/blob/f06c58911515d980e25c33874c5f18ade5ac99df/packages/react-refresh-utils/ReactRefreshWebpackPlugin.ts), but would mean quite a change as we'll have to split the plugin into 4 and 5 versions.

**Comment by honzahk** [comment]
Anyone solved this problem already?

I get error `Module '"webpack"' has no exported member 'Plugin'` inside `node_modules\nodemon-webpack-plugin\dist\index.d.ts`.

Here are dependecies from my package.json:
``` json
{
    "devDependencies": {
        "nodemon-webpack-plugin": "^4.4.4",
        "ts-loader": "^8.0.18",
        "ts-node": "^9.1.1",
        "typescript": "^4.2.3",
        "webpack": "^5.27.2",
        "webpack-cli": "^4.5.0"
    }
}
```

How do i fix this error?

**Comment by Izhaki** [comment]
The typings issue was declared by the WebPack team as a breaking change between v4 and v5.

We have two options:
1. Split the plugin.
2. Create our own types (like [html-webpack-plugin did](https://github.com/jantimon/html-webpack-plugin/blob/3768bbabb7bfc19487f94841f0e7d4900bca7110/typings.d.ts)).

Second option seems far more reasonable to me.

Will attempt fix in due course.

**Comment by Izhaki** [comment]
Landed as [4.50](https://www.npmjs.com/package/nodemon-webpack-plugin/v/4.5.0).

@honzahk Can you let me know if we are all good after update?

**Comment by agramian** [comment]
I updated to 4.5.0 and am still experiencing this issue.

I've provided the stacktrace below.
Let me know if I'm missing anything setup-wise in terms of webpack or TypeScript configuration to support this plugin on webpack 5.  I was previously using this plugin without issue on webpack 4.  Let me know if I can provide any additional info to help resolve this.
```
[webpack-cli] webpack.dev.ts:1:27 - error TS7016: Could not find a declaration file for module 'nodemon-webpack-plugin'. '/path/to/project/node_modules/nodemon-webpack-plugin/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/nodemon-webpack-plugin` if it exists or add a new declaration (.d.ts) file containing `declare module 'nodemon-webpack-plugin';`

  import NodemonPlugin from 'nodemon-webpack-plugin';
```

In case it helps you debug, I'm also using TypeScript for my webpack config since they started supporting that (https://webpack.js.org/configuration/configuration-languages/).

**Comment by agramian** [comment]
Using `import NodemonPlugin = require('nodemon-webpack-plugin');` resolves this and now after trying the plugin again with Webpack 5 it works properly.

**Comment by agramian** [comment]
Actually I was only able to get this to work by having TypeScript ignore the import line like below:
```
// @ts-ignore
import NodemonPlugin from 'nodemon-webpack-plugin';
```
Regardless, it now works with Webpack 5.

**Comment by Izhaki** [comment]
Hi @agramian 

I'm reopening this issue as there is clearly still an issue:

```
error TS7016: Could not find a declaration file for module 'nodemon-webpack-plugin'.
```

Adding `// @ts-ignore` ignores the typings for the plugin, which is a work around.

I'll investigate and release a patch.

**Comment by honzahk** [comment]
@Izhaki

yeah, getting the same error with nodemon-webpack-plugin v 4.5.0 as i use typescript for my webpack.config.ts too

as the error states, it seems the declaration file `node_modules\nodemon-webpack-plugin\dist\index.d.ts` is not generated in the v 4.5.0

**Comment by Izhaki** [comment]
The location of the typing files has changed (and it's now sibling to `package.json`, not under `dist`):

```
   "types": "typings.d.ts",
```

@honzahk @agramian Does any of you guys have a public repo I can pull to try this on? Else I'll have the extra overhead of setting up something locally.

Also, out of interest, how do you guys get the webpack.config.ts to transplie? ts-node? @babel/node?

**Comment by agramian** [comment]
I use ts-node and in regard to a public repo I can put something minimal together and put the link here once its up.

**Comment by honzahk** [comment]
@Izhaki 

heres the minimal repo https://github.com/honzahk/test0/tree/master

**Comment by honzahk** [comment]
@Izhaki

heres the minimal repo https://github.com/honzahk/test0/tree/master

and yes, if you create webpack.config.ts and run webpack, it automatically tells you to install one of the libs (i use ts-node too)

```
$ webpack
[webpack-cli] Unable load 'path-to-project\webpack.config.ts'
[webpack-cli] Unable to use specified module loaders for ".ts".
[webpack-cli] Cannot find module 'ts-node/register' from 'path-to-project'
[webpack-cli] Cannot find module 'typescript-node/register' from 'path-to-project'
[webpack-cli] Cannot find module 'typescript-register' from 'path-to-project'
[webpack-cli] Cannot find module 'typescript-require' from 'path-to-project'
[webpack-cli] Cannot find module 'sucrase/register/ts' from 'path-to-project'
[webpack-cli] Cannot find module '@babel/register' from 'path-to-project'
[webpack-cli] Please install one of them
```

**Comment by agramian** [comment]
@Izhaki here's another one as well if it helps https://github.com/agramian/fastify-examples/tree/webpack-typescript (link is to the branch to look at, don't just use the main branch).

**Comment by Izhaki** [comment]
@honzahk @agramian Thank you so much for you help.

This may take a bit longer, so would really appreciate if you can stay around and report back on fixes.

> Heres the minimal repo https://github.com/honzahk/test0/tree/master

Thanks, this has been really useful!

> In v 4.5.0, type declaration file should be sibling to package.json, unfortunately it is not

Correct! I have not added it to `files` in `package.json`.

Just published [v4.5.1](https://www.npmjs.com/package/nodemon-webpack-plugin/v/4.5.1) - can you give it a try?

**Comment by Izhaki** [comment]
# Note to Self

with

```
apply(compiler: webpack.Compiler): void;
```

I got

```
error TS2321: Excessive stack depth comparing types 'NodemonPlugin' and '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance'.
```

([One of many related issues](https://github.com/microsoft/TypeScript/issues/37600))

So I had to change to:

```
apply(compiler): void;
```

---

Also, would like to note [this issue](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/534) on `fork-ts-checker-webpack-plugin`, where the author states:

```
Note that updating the types to support webpack v5 will probably break compatibility with webpack v4. From what I've seen with other plugins, it's an either-or situation...
```

Now their's is much heavier use case, but as far as basic typings is concerned, the approach taken here might work and this also appears to work:

```
type Plugin = webpack.Plugin | webpack.WebpackPluginInstance;

declare class NodemonPlugin implements Plugin { ... }
```

**Comment by honzahk** [comment]
Confirmed, the types are correct now (v4.5.1) and I am able to compile without workarounds.

Thanks a lot!

**Comment by Izhaki** [comment]
@agramian Any luck?

**Comment by agramian** [comment]
Yes it now works without needing `// @ts-ignore` above the import however it only works when importing using the `require` syntax. So it might be helpful to document that in the readme or somewhere if it's not already.

```
// This works.
import NodemonPlugin = require('nodemon-webpack-plugin');

// This throws an error with my setup and TypeScript config.
import NodemonPlugin from 'nodemon-webpack-plugin';
```

**Comment by Izhaki** [comment]
```
// This throws an error with my setup and TypeScript config.
import NodemonPlugin from 'nodemon-webpack-plugin';
```

I'm afraid this has to do with the whole CommonJS/ES6 mismatch, and I've documented this [in the type definitions](https://github.com/Izhaki/nodemon-webpack-plugin/blob/e6055e608620940d612c7b9fd30260e2eb062455/typings.d.ts#L3-L6):

```typescript
// We prioritise supporting CommonJS than ES6 syntax here.
// Typescript users will have to add `esModuleInterop` in `compilerOptions`.
// https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require
export = NodemonPlugin;
```

Basically, you need to choose between CommonJS (`export =`) and ES6 (`export default`). If you opt for the latter, than CommonJS scripts will have to import the plugin like this (note `.default`):

```javascript
const NodemonPlugin = require('nodemon-webpack-plugin').default; 
```

I've prioritise the CommonJS export based on a (rather reasonable in my view) assumption that most users don't have their `webpack.config.js` transpiled.
