### ISSUE TITLE
nodemon-webpack-plugin troubles on VM WSL-2.

### ISSUE THREAD

**Issue by nekithockey75** [Izhaki/nodemon-webpack-plugin#119]
When running WSL-2 which uses virtualization need to pass `-L` legacy flag to node.

`nodemon -L <dirname>`

May be this will save you some time.

**Comment by Izhaki** [comment]
Thanks for this, from the [nodemon docs](https://github.com/remy/nodemon#application-isnt-restarting):

> you will need to use the `legacyWatch: true` which enables Chokidar's polling.

That's what you're after no?
