### ISSUE TITLE
Pass environment variables to script

### ISSUE THREAD

**Issue by bryanvaz** [Izhaki/nodemon-webpack-plugin#127]
Quick question: Is there an existing way to pass environment variables to the script?

_(If not I'll write a patch and PR)_

Cheers,
Bryan

**Comment by Izhaki** [comment]
Node mode has an `env` option. See [this sample config file](https://github.com/remy/nodemon/blob/master/doc/sample-nodemon.md).

The plugin simply delegates the options provided to nodemon. So this should do it:

```
  plugins: [
    new NodemonPlugin({
      env: {
        NODE_ENV: "development"
      }
    }),
  ],
```

Could you let me know if this works?

**Comment by Izhaki** [comment]
I've just check and this works:

```
  plugins: [
    new NodemonPlugin({
      env: {
        NODE_ENV: "development"
      }
    }),
  ],
```

README updated with `env` option.
