### ISSUE TITLE
How to use with multiple webpack configs?

### ISSUE THREAD

**Issue by krutoo** [Izhaki/nodemon-webpack-plugin#128]
Hi, how can i run script by this plugin after several bundle was emitted?

My webpack config looks like:
```js
module.exports  = [
  { /* first (client) bundle... */ },
  { 
    target: 'node'
    /* second (server) bundle... */
    plugins: [
       new NodemonPlugin(),
    ],
  },
];
```

When nodemon runs script from server bundle, client bundle is not emmited (not written on disk)

How can i run nodemon only after all bundles written on disk?

UPD: this is due to parallel configurations and `parallelism: 1` option solves this issue but it negatively affects performance maybe

**Comment by krutoo** [comment]
Looks like `dependencies` property of config object solves this issue:

more details:
https://github.com/webpack/webpack.js.org/issues/4685#issuecomment-790589004

**Comment by Izhaki** [comment]
Cool. So can we close the issue?

**Comment by krutoo** [comment]
@Izhaki yes
