### ISSUE TITLE
cannot capture complication failure on webpack 5.32.0

### ISSUE THREAD

**Issue by tiejunhu** [Izhaki/nodemon-webpack-plugin#129]
Nice plugin!

But it seems cannot capture complication failure with webpack 5.32.0.

my webpack config :

![image](https://user-images.githubusercontent.com/105164/115944202-eff24f00-a4e6-11eb-99d8-dd2ea47330ab.png)

and when complication fail, it continues to restart, rather than display the error message:

![image](https://user-images.githubusercontent.com/105164/115944216-06000f80-a4e7-11eb-9d34-c51552675d23.png)

**Comment by tiejunhu** [comment]
I found the plugin did capture the compile error but still restart the app. I suppose it should not restart the app, right?

**Comment by Izhaki** [comment]
> I suppose it should not restart the app, right?

Good question.

If I remember correctly this was the line of thinking:

- You have the plugin running at the background. You don't always watch the console output.
- You edit your code, which has errors.
- If we do not restart the server, the server still runs - based on the previous, working, code - and you have no way of knowing something went wrong...

So the idea of restarting the server would cause it to go down, and then you know somethings wrong.

More than happy to discuss this scenario and the preferred user behaviour.

**Comment by tiejunhu** [comment]
The problem is typescript. typescript will generate errors AND still generate output javascript files, which lead to nodemon restart the app. So in my workflow, the output of the restarted application scroll the typescript compiler error far out of screen.

I now fix this behavior with an option "noEmitOnError": true in tsconfig.json. This option has some flaws, but basically work for my case.

So you may consider optimize this workflow, or close this issue as it's kind of resolved.

**Comment by Izhaki** [comment]
I fear that introducing any type of new logic will break the whole design principle of this plugin - simply delegating to `nodemon` options.

The `noEmitOnError` seems very reasonable solution to this use case, so closing.

**Comment by leppaott** [comment]
Even with `noEmitOnError` isn't the old build still there to be run? Which this does as `tsc` or `webpack` unlikely delete the output. I'm running `webpack --watch` on docker with this plugin and it's quite unusable as the build errors are on top flooded with applications logs that still starts. Isn't there a way to capture that webpack error?

Works with tsc-watch and nodemon:
`"tsc-watch -b --noClear --onFirstSuccess \"nodemon index.js\"`

```
 11:53:11 AM - File change detected. Starting incremental compilation...

 src/index.ts(20,1): error TS2304: Cannot find name 'FUU'.
 1:53:12 AM - Found 1 error. Watching for file changes.
```

**Comment by leppaott** [comment]
@Izhaki

```
So the idea of restarting the server would cause it to go down, and then you know somethings wrong.
```
Better to get the error from the building tool than to let it crash if it does - which not always happens. For an example ts-loader catches typos on variables:
```
ERROR in ./src/index.ts:94:17
TS2551: Property 'EXAMPLE_POR' does not exist on type 'ProcessEnvs'. Did you mean 'EXAMPLE_PORT'?
processEnvs.EXAMPLE_POR,
```
This of course executes as undefined and continues as usual unless you do null checking everywhere.
