### ISSUE TITLE
Support for nodemon reload

### ISSUE THREAD

**Issue by rdsedmundo** [Izhaki/nodemon-webpack-plugin#136]
It'd be good to have a way to reload by sending `reload` in the stdin, like the real `nodemon` CLI allows. Not sure if we can control this over a plugin since webpack is managing the process though,

**Comment by Izhaki** [comment]
I can see why this would be useful, but this is outside the scope of the plugin.

By definition, this plugin merely delegates things to nodemon - it doesn't have its own API.

I curious about when and why you'd like to send a reload, and from which bit of your code this will be trigger?

**Comment by rdsedmundo** [comment]
Sometimes the process crashes, or I just want to start from scratch when doing something in the CLI, without going back to the editor and touching a file.

https://github.com/remy/nodemon#manual-restarting

**Comment by Izhaki** [comment]
> Whilst nodemon is running, if you need to manually restart your application, instead of stopping and restart nodemon, you can type rs with a carriage return, and nodemon will restart your process.

You do this on the terminal? Does this not work with the plugin?

**Comment by Izhaki** [comment]
Closing as stale. Happy to re-open upon renewed activity.

**Comment by Bessonov** [comment]
I've discovered this plugin today and it's amazing @Izhaki !

@rdsedmundo just typing `rs` works for me.
