### ISSUE TITLE
How to watch non-webpack files?

### ISSUE THREAD

**Issue by Jakobud** [Izhaki/nodemon-webpack-plugin#14]
How do you use this to watch files that aren't apart of your webpack bundle/dist ? For example watching your node.js server files or your template file changes?? It doesn't seem to pick up anything at all.

**Comment by Izhaki** [comment]
Hmmm... very similar issue to #13 in close proximity...

And I assume you have tried both `watch` and `script` properties of the config?

The plugin only delegates to nodemon. It should work.

Any way I can reproduce this issue myself?

**Comment by Jakobud** [comment]
Ah I think I got it to work right using this:

```
plugins: [
    new NodemonPlugin({
      script: './bin/www',
      ext: 'js json njk',
      watch: '.'
    })
  ]
```

So in this case it's watching for changes to `.js`, `.json` and `.njk` files in all subdirectories because I'm using the watch path as `.`. This seems to work okay.
