### ISSUE TITLE
Typescript errors with Webpack 5

### ISSUE THREAD

**Issue by misak-yt** [Izhaki/nodemon-webpack-plugin#164]
when i build tsconfig.json with ”tsc -b tsconfig”

```
node_modules/webpack/types.d.ts:91:10 - error TS2305: Module '"schema-utils/declarations"' has no exported member 'validate'.

91 import { validate as validateFunction } from "schema-utils";
            ~~~~~~~~


Found 1 error.
```

i fixed at node_modules\webpack\types.d.ts from
`import { validate as validateFunction } from "schema-utils"`
to
`import { default as validateFunction } from "schema-utils/declarations/validate";`

**Comment by Izhaki** [comment]
Sorry, but what does it have to do with the plugin?

Neither the problem nor the solution mention it?
