### ISSUE TITLE
show stacktrace of the error

### ISSUE THREAD

**Issue by sibelius** [Izhaki/nodemon-webpack-plugin#167]
I'm getting this error

```
[nodemon] app crashed - waiting for file changes before starting...
```

how can I show the full error ?

**Comment by Izhaki** [comment]
This message is from Nodemon, not the plugin.

There's a [related issue on the nodemon repo](https://github.com/remy/nodemon/issues/1990). I reckon you should ask there.

**Comment by sibelius** [comment]
someone is swallowing the error

**Comment by Izhaki** [comment]
Closed due to inactivity / unclarity.
