### ISSUE TITLE
support webpack 4

### ISSUE THREAD

**Issue by gferreri** [Izhaki/nodemon-webpack-plugin#19]
the peer dependencies only list webpack 2 and 3. Therefore it cannot be cleanly used with webpack 4 or npm will generate peer dependency warnings

```
npm WARN nodemon-webpack-plugin@3.0.1 requires a peer of webpack@^2 || ^3 but none is installed. You must install peer dependencies yourself.
```

**Comment by Izhaki** [comment]
Webpack 4 version is on the `webpack4` branch:

https://github.com/Izhaki/nodemon-webpack-plugin/tree/webpack4

**Comment by benedikthth** [comment]
that does not work. Am getting an error of: 
`(node:16676) DeprecationWarning: Tapable.plugin is deprecated. Use new API on '.hooks' instead`

package.json dependency:   
    `"nodemon-webpack-plugin": "^4.0.3", `

**Comment by Izhaki** [comment]
@benedikthth 

Something is very very oddly wrong here.

The DeprecationWarning you get will show if you use the webpack3 API with webpack4.

If you look at [the source code for 4.x](https://github.com/Izhaki/nodemon-webpack-plugin/blob/webpack4/src/index.js) it only uses the `.hooks` API.

Could you have a look at your `node_modules/nodemon-webpack-plugin` and confirm the correct version is installed?

**Comment by benedikthth** [comment]
the warning disappears when i comment nodemon-w-p out of webpack.conf.js

in node_modules/nodemon-webpack-plugin/package.json the following two attributes can be found
` "_id": "nodemon-webpack-plugin@4.0.3",`
and
`"version": "4.0.3"`

I am quite confused, since this error is not encountered at all with any of my other plugins.

**Comment by Izhaki** [comment]
@benedikthth is there a repo I can look at?

Also, might have something to do with webpack itself - which version is installed for you?

**Comment by benedikthth** [comment]
webpack -v yields `4.8.3`

and the repository is [here](https://github.com/benedikthth/HvittBros)

Right now i'm just restarting the server like an idiot, so i'm super excited to use your plugin if it works!

**Comment by Izhaki** [comment]
@benedikthth I suspect this is the globally installed webpack version.

[`package.json` on the repo you've link has](https://github.com/benedikthth/HvittBros/blob/master/package.json#L33):

```
    "webpack": "^3.12.0",
```

Having ran

    npm install
    npm run build

I get:

```
$ npm run build

> hvittbros@1.0.0 build /Volumes/Data/Development/tbd/HvittBros
> webpack

/Volumes/Data/Development/tbd/HvittBros/node_modules/webpack/bin/webpack.js:348
			throw err;
			^

TypeError: Cannot read property 'afterEmit' of undefined
    at _class.apply (/Volumes/Data/Development/tbd/HvittBros/node_modules/nodemon-webpack-plugin/dist/index.js:46:22)
```

Which is consistent with a webpack4 plugin using webpack3.

**Comment by benedikthth** [comment]
ok! so turns out that removing extracttextplugin makes it run smoother, also, wrong local version of webpack. sorry to bother you have a nice day!

**Comment by Izhaki** [comment]
No worries @benedikthth 
@gferreri You good?

**Comment by gferreri** [comment]
Yep, I'm good. I missed that line in the README. Thanks!
