### ISSUE TITLE
No way to pass argv to script launched by plugin

### ISSUE THREAD

**Issue by ThisIsRuddy** [Izhaki/nodemon-webpack-plugin#2]
Hi, I have been battling all night to find a way to pass argv values to the script being launched by the `nodemon-webpack-plugin`.

This is my production command: `nodemon dist/server.bundle.min.js container`

For my production testing, you can see I pass the following argv value: 'container'. This is then parsed in to `server.bundle.min.js ` using `process.argv` to use the value for further app logic.

Unfortunately, I cannot see a way to pass this argv value to the `nodemon-webpack-plugin` to achieve the same manner I which I use `nodemon` for my production command.

Have I missed something? Can this be done? 
Or could we possibly attempt to write and implement something along the lines of use similar to the following?
```const NoDemonPlugin = require('nodemon-webpack-plugin');
module.exports = {
...
plugins: [
    new NoDemonPlugin({
        argv: [
           "argvOne",
           "argvTwo",
           "argvThree"
        ]
    })
]
...
//equivelent to running
//nodemon dist/server.bundle.min.js argvOne argvTwo argvThree
```

Let me know your thoughts :) 

This would help me out alot!

**Comment by Izhaki** [comment]
You haven't miss anything. As the 'zero-configuration' suggests, there currently no way to do this.

Yet this seems like a reasonable use-case, although would be nice to get some more details... like why providing `container` to a server? What is `container`?

Shouldn't be too hard to implement either...

**Comment by ThisIsRuddy** [comment]
Hi izhaki, thanks for getting back to me and the use case of 'container' is
simply app specific.

But in my use case: simply passing this variable allows me to run the
server in a container and locally on different ports as well as allowing
the same npm scripts commands in the same manner. I know this all sounds
abit scatty but it's rather difficult to explain as it is a docker/local
work flow for production and development environments however, the purposes
of passing argv values to the script are endless depending on app I guess 😊

**Comment by Izhaki** [comment]
Not ruling out the use case, but isn't the standard way to achieve this is using either an environment variable or docker's port mapping?

If your apps are to scale you'll find it a hell relying on `argv` for all things docker.

(You should also consider that your server may not be the entry point / last command in a Dockerfile, so relying on argv makes is slightly less easy to configure.)

Possibly there's a much better way to achieve what you're after?

**Comment by ThisIsRuddy** [comment]
Ahaa yeah I have used and I am still using environment variables and port
mappings with networked containers with shared volumes etc.

In my current app it is simply telling the server to run some different
configuration depending on whether the app was started in the container or
a local environment.

**Comment by Izhaki** [comment]
I'm going to leave this one open for now, I guess if one or two more people come up with a compelling use case we should do this.

**Comment by Izhaki** [comment]
Just submitted a PR.

You should be able to pass args like so:

```javascript
new NodemonPlugin({
    /// Arguments to pass to the script being restarted
    args: ['demo'],
})
```

Let me know if it works for you.
