### ISSUE TITLE
Bump nodemon version to avoid security issue

### ISSUE THREAD

**Issue by jasonwilliams** [Izhaki/nodemon-webpack-plugin#23]
Issue here: https://github.com/dominictarr/event-stream/issues/116
I'm not sure if nodemon has pushed an update, but nodemon@latest AKA 1.18.6 has the fix.

**Comment by Izhaki** [comment]
OK. This is actually Nodemon@1.11.0 > ps-tree^1.0.1 > event-stream.

https://github.com/indexzero/ps-tree/issues/33

**Comment by Izhaki** [comment]
Just published.
Tests fail - will solve in due course.

THANKS!!!!!!!!!!!!

**Comment by Izhaki** [comment]
Turns out the [issue was actually with nodemon itself](https://github.com/remy/nodemon/issues/1463) - not killing child processes properly.

So there's another release (4.0.6) and is worth upgrading to.
