### ISSUE TITLE
is:issue is:open attempting to run `ps` ?

### ISSUE THREAD

**Issue by Spongman** [Izhaki/nodemon-webpack-plugin#54]
this is on windows with all latest bits. all i have done is added the following to my `webpack.config.js`: 

````
const NodemonPlugin = require('nodemon-webpack-plugin');
````

when i run `webpack --watch`, now i get this popup:

![image](https://user-images.githubusercontent.com/1088194/62014267-a0d18b80-b153-11e9-9db8-9db6b6281483.png)

if i remove the `require` line, the popup doesn't show.

**Comment by Izhaki** [comment]
Hi. Sorry for the belated reply. Was on a holiday.

Having googled the issue, I strongly suspect this has something to do with the `child-process-promise` dependency, which uses `cross-spawn`, which is the one lunching `nodemon`.

1. You may want to have a look for a similar issue under [cross-spawn repo](https://github.com/moxystudio/node-cross-spawn)
2. child-process-promise hasn't been updated for 3 years, so I may replace it in the coming week. This may solve the issue.

Watch this space.

**Comment by Izhaki** [comment]
Actually, `child-process-promise` is a dev dependency. So should have nothing to do with this issue at all.

Are you even adding the plugin or is it just that line that messes things up?

I don't reckon this is an issue with the plugin, so closing.

But please do reply if still an issue / new information.
