### ISSUE TITLE
inspect or debug flag example?

### ISSUE THREAD

**Issue by JasonKleban** [Izhaki/nodemon-webpack-plugin#8]
Continuing from https://github.com/remy/nodemon/issues/1114

I've tried: 

```
new NodemonPlugin({ debug: true})
new NodemonPlugin({ inspect: true})
new NodemonPlugin({ inspect: 9229 }) 
new NodemonPlugin({ nodeArgs: { debug: true } })
new NodemonPlugin({ nodeArgs: { inspect: true } })
new NodemonPlugin({ nodeArgs: { inspect: 9229 } })
```

But none of them seem to serve the debugger stuff.  What's the right way?

Thanks!

**Comment by Izhaki** [comment]
Looking at [nodemon's tests](https://github.com/remy/nodemon/blob/be5d4e8d13a6dcc16c65b5bce59edef54496a8ae/test/cli/exec.test.js#L36):

```javascript
  it('should support --debug=XXXX', function () {
    var options = exec({ script: 'app.js', nodeArgs: [ '--debug=9999' ]});
    var cmd = toCmd(options);
    assert(cmd.string === 'node --debug=9999 app.js', cmd.string);
    assert(options.exec === 'node');
    assert(options.ext.indexOf('js') !== -1);
  });
```

So have you tried:

```javascript
new NodemonPlugin({ nodeArgs: [ '--debug=9999' ] })
```

At least on the tests it seems to do the right thing:

```
[nodemon] starting `node --debug=9999 ../../../../../private/var/folders/wc/3ghj3xvj4mv9k4b_6ssk6_g80000gn/T/tmp-20561J5vh8ynId9nV/dist/server.js --port 4096`
```

**Comment by JasonKleban** [comment]
Excellent.  Thanks!

**Comment by Izhaki** [comment]
I've updated the README to include the example above.

Thanks!

**Comment by DivekJohns** [comment]
any example on typescript?
webpack.config.ts
  plugins: [
    new NodemonPlugin({ nodeArgs: [ "--debug=9999" ] }), // not working
  ],

[nodemon] starting `ts-node ./src/main.ts build\main.js`

**Comment by Izhaki** [comment]
@DivekJohns Not sure what is being asked or what you are trying to achieve. What I don't understand:

Is this your plugin config?

```
new NodemonPlugin({ nodeArgs: [ "--debug=9999" ] }), // not working
```

What's this:

```
[nodemon] starting ts-node ./src/main.ts build\main.js
```

- Where is ts-node coming from?
- Why both `./src` AND build\main.js`?

Could you kindly clarify?
