### ISSUE TITLE
`getOutputFileName` doesn't work with multiple chunks

### ISSUE THREAD

**Issue by kimniche** [Izhaki/nodemon-webpack-plugin#9]
As-is, the logic in `getOutputFileName` doesn't seem to account for grabbing the right "main" output file when multiple chunks are produced, for ex with dynamic imports. In this case, I think you would want `R.last` here, instead of `R.head`, since Webpack will generate the main output file after the dynamic chunks:

https://github.com/Izhaki/nodemon-webpack-plugin/blob/master/src/webpack-utils.js#L9

PS. Thanks for a great plugin!!

**Comment by Izhaki** [comment]
Isn't 'R.last' and 'R.head' are just guesses in the case of multi-entry?

If we are to support multi-entry, shouldn't the one to be watched be provided explicitly to the plugin (which you can already do by overriding the `script` property in the config)?

**Comment by kimniche** [comment]
Ah okay, tbh I completely missed the `script` option -- that totally solves my issue. Thanks!

**Comment by Izhaki** [comment]
I should probably update the README to demonstrate this use case.

Leaving this issue open for now.

**Comment by Izhaki** [comment]
There will still be a problem if the the output files are hashed - in which case we'll HAVE to add an explicit option, which is kind of nasty as currently the config is purely the nodemon one (so it will be a breaking change)...

**Comment by kimniche** [comment]
Yeah it's a tricky one.. if it helps at all, originally I was trying to look into other webpack plugins to coerce the ordering of output more deterministically but wasn't having much luck there

**Comment by Izhaki** [comment]
I've updated the README to show example of using `script`.

Closing this issue - will deal with the issue of hashed multiple entries when someone actually has such an issue.
