### ISSUE TITLE
New npm release?

### ISSUE THREAD

**Issue by javorosas** [Izhaki/nodemon-webpack-plugin#93]
There are some changes in `nodemon 2.0.2` that I'm interested in, namely a fix for running nodemon inside docker.

Mind to publish a new release?

**Comment by Izhaki** [comment]
Done! Landed as [4.2.2](https://www.npmjs.com/package/nodemon-webpack-plugin)

**Comment by javorosas** [comment]
Awesome! Thanks 🙏
